//
// Created by Filip Dabkowski on 28/11/2023.
//

#ifndef BACKGAMMONGAME_MENUCONFIGS_H
#define BACKGAMMONGAME_MENUCONFIGS_H

#define N_GAME_MENU_OPTIONS 4
#define N_STARTER_MENU_OPTIONS 3
#define N_PIECE_MENU_OPTIONS 2

#endif //BACKGAMMONGAME_MENUCONFIGS_H
